# Generated by Django 6.0.7 on 2026-08-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='est_favori',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='est_lu',
            field=models.BooleanField(default=True),
        ),
    ]
