# Generated by Django 6.0.7 on 2026-07-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('type_notification', models.CharField(choices=[('validation', 'Document validé'), ('rejet', 'Document rejeté'), ('acces_accorde', 'Accès à un document accordé')], max_length=20)),
                ('lue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('email_envoye', models.BooleanField(default=False)),
                ('date_envoi_email', models.DateTimeField(blank=True, null=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='documents.document')),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-date_creation'],
            },
        ),
    ]
