# Generated by Django 6.0.7 on 2026-09-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_apercu_pdf'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='type_notification',
        ),
        migrations.AddField(
            model_name='notification',
            name='date_lecture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Notification', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('validation', 'Validation'), ('rejet', 'Rejet'), ('partage', 'Partage'), ('acces_accorde', 'Accès accordé'), ('nouveau_document', 'Nouveau document')], default='nouveau_document', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_lien', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
    ]
