# Generated by Django 6.0.7 on 2026-07-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine_email_autorise', models.CharField(blank=True, default='@dta-alliance.com', help_text="Ex: @dta-alliance.com — laisser vide pour accepter n'importe quel domaine d'email", max_length=255)),
                ('derniere_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, help_text='Dernier administrateur ayant modifié cette configuration', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration de connexion',
                'verbose_name_plural': 'Configuration de connexion',
            },
        ),
    ]
