# Generated by Django 6.0.7 on 2026-07-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_changement_mdp_obligatoire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationconnexion',
            name='domaine_email_autorise',
            field=models.CharField(blank=True, default='@dta-alliance.com,@gmail.com', help_text="Domaines séparés par des virgules, ex: '@dta-alliance.com,@gmail.com' — laisser vide pour accepter n'importe quel domaine", max_length=255),
        ),
    ]
