# Generated by Django 6.0.7 on 2026-07-22 09:00

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_configurationconnexion_domaine_email_autorise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilutilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.chemin_photo),
        ),
    ]
