# Generated by Django 6.0.7 on 2026-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profilutilisateur_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomaineEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(help_text='Ex: dta-alliance.com ou gmail.com (sans le @)', max_length=100, unique=True)),
                ('actif', models.BooleanField(default=True, help_text='Décochez pour désactiver ce domaine temporairement')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domaine email autorisé',
                'verbose_name_plural': 'Domaines emails autorisés',
                'ordering': ['-actif', 'domaine'],
            },
        ),
        migrations.AlterField(
            model_name='configurationconnexion',
            name='domaine_email_autorise',
            field=models.CharField(blank=True, default='@dta-alliance.com,@gmail.com', help_text='Obsolète : Utilisez la gestion des domaines ci-dessous.', max_length=255),
        ),
    ]
