# Generated by Django 6.0.7 on 2026-07-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_domaineemail_and_more'),
        ('documents', '0005_departement_document_cause_rejet_document_favoris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='departement',
            field=models.ForeignKey(blank=True, help_text="Département auquel l'utilisateur appartient.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='documents.departement'),
        ),
    ]
