# Generated by Django 6.0.7 on 2026-07-23 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profilutilisateur_departement'),
        ('documents', '0005_departement_document_cause_rejet_document_favoris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='departements_autorises',
            field=models.ManyToManyField(blank=True, help_text="Départements supplémentaires auxquels l'admin a donné accès à cet utilisateur.", related_name='acces_externe', to='documents.departement'),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='departement',
            field=models.ForeignKey(default=1, help_text="Département principal auquel l'utilisateur appartient (Obligatoire).", on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='documents.departement'),
            preserve_default=False,
        ),
    ]
