# Generated by Django 6.0.7 on 2026-08-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profilutilisateur_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='Numéro de téléphone pour recevoir le code 2FA par SMS (optionnel).', max_length=30),
        ),
    ]
