# Generated by Django 6.0.7 on 2026-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profilutilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='code_2fa',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='code_2fa_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='token_2fa_temporaire',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='profilutilisateur',
            name='telephone',
            field=models.CharField(blank=True, default='', help_text='Numéro de téléphone (optionnel).', max_length=30),
        ),
    ]
