# Generated by Django 6.0.7 on 2026-08-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profilutilisateur_code_2fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='tentatives_2fa_echouees',
            field=models.IntegerField(default=0),
        ),
    ]
