# Generated by Django 6.0.7 on 2026-08-04 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profilutilisateur_tentatives_2fa_echouees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='date_derniere_demande_code',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='nb_codes_envoyes_heure',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AppareilApprouve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nom_appareil', models.CharField(blank=True, default='', max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils_approuves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
