# Generated by Django 6.0.7 on 2026-08-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profilutilisateur_date_derniere_demande_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationconnexion',
            name='two_fa_obligatoire',
            field=models.BooleanField(default=False, help_text='Si True, tous les utilisateurs devront utiliser la double authentification à la connexion.'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='two_fa_active',
            field=models.BooleanField(default=False, help_text="Si True, l'utilisateur a activé la double authentification pour son compte."),
        ),
    ]
