# Generated by Django 6.0.7 on 2026-09-11 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_configurationconnexion_two_fa_obligatoire_and_more'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAppareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appareil', models.CharField(blank=True, default='', max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('est_active', models.BooleanField(default=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='authtoken.token')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session appareil',
                'verbose_name_plural': 'Sessions appareils',
                'ordering': ['-cree_le'],
            },
        ),
    ]
