# Generated by Django 6.0.7 on 2026-07-08 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/')),
                ('type_source', models.CharField(choices=[('numerique', 'Fichier numérique'), ('scan', 'Document papier scanné')], default='numerique', max_length=20)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='Taille en octets', null=True)),
                ('type_mime', models.CharField(blank=True, max_length=100)),
                ('auteur_document', models.CharField(blank=True, help_text='Auteur détecté dans les métadonnées du fichier', max_length=255)),
                ('contenu_texte', models.TextField(blank=True, help_text="Texte extrait (lecture directe ou OCR) pour l'indexation")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('en_cours', 'Traitement en cours (ETL)'), ('valide', 'Validé et indexé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('log_pipeline', models.JSONField(blank=True, default=list, help_text='Historique des étapes ETL avec horodatage')),
                ('est_confidentiel', models.BooleanField(default=False)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.categorie')),
                ('depose_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_deposes', to=settings.AUTH_USER_MODEL)),
                ('utilisateurs_autorises', models.ManyToManyField(blank=True, help_text='Si le document est confidentiel, liste des utilisateurs ayant accès en plus du déposant', related_name='documents_autorises', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='documents.tag')),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-date_depot'],
            },
        ),
    ]
