# Generated by Django 6.0.7 on 2026-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='hauteur_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='largeur_px',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
