# Generated by Django 6.0.7 on 2026-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_date_derniere_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='groupe',
            field=models.CharField(blank=True, help_text='documents / images / media / autres', max_length=20),
        ),
    ]
