# Generated by Django 6.0.7 on 2026-07-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='duree',
            field=models.FloatField(blank=True, help_text='Durée en secondes (vidéo/audio)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='est_epingle',
            field=models.BooleanField(default=False, help_text='Document épinglé en haut des listes'),
        ),
        migrations.AddField(
            model_name='document',
            name='tentative_count',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de tentatives du pipeline ETL'),
        ),
        migrations.AddField(
            model_name='tag',
            name='couleur',
            field=models.CharField(blank=True, default='#6366f1', help_text='Couleur hexadécimale du tag', max_length=7),
        ),
    ]
