# Generated by Django 6.0.7 on 2026-07-21 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_duree_document_est_epingle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='cause_rejet',
            field=models.TextField(blank=True, help_text='Cause du rejet si statut=rejete'),
        ),
        migrations.AddField(
            model_name='document',
            name='favoris',
            field=models.ManyToManyField(blank=True, related_name='documents_favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='auteur_document',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='contenu_texte',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='duree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='est_epingle',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='groupe',
            field=models.CharField(blank=True, help_text='documents / images / medias', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='log_pipeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='document',
            name='taille_fichier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='tentative_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='utilisateurs_autorises',
            field=models.ManyToManyField(blank=True, related_name='documents_autorises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='couleur',
            field=models.CharField(blank=True, default='#6366f1', max_length=7),
        ),
        migrations.CreateModel(
            name='ConnexionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de connexion',
                'ordering': ['-date_connexion'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.departement'),
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('suppression', 'Suppression'), ('rejet', 'Rejet ETL'), ('modification', 'Modification')], max_length=20)),
                ('cause', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='documents.document')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'action",
                'ordering': ['-date_action'],
            },
        ),
    ]
