# Generated by Django 6.0.7 on 2026-07-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_departement_document_cause_rejet_document_favoris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='departements_autorises',
            field=models.ManyToManyField(blank=True, help_text='Départements supplémentaires autorisés à voir ce document', related_name='documents_autorises', to='documents.departement'),
        ),
    ]
