# Generated by Django 6.0.7 on 2026-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_departements_autorises'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='miniature',
            field=models.ImageField(blank=True, help_text='Aperçu généré automatiquement (1ère page pour les PDF)', null=True, upload_to='miniatures/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='logaction',
            name='type_action',
            field=models.CharField(choices=[('suppression', 'Suppression'), ('rejet', 'Rejet ETL'), ('validation', 'Validation ETL'), ('modification', 'Modification')], max_length=20),
        ),
    ]
