# Generated by Django 6.0.7 on 2026-07-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_miniature_alter_logaction_type_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='nom_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
