# Generated by Django 6.0.7 on 2026-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_departement_nom_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('disk_used_gb', models.FloatField()),
                ('disk_total_gb', models.FloatField()),
                ('minio_used_gb', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Snapshot stockage',
                'verbose_name_plural': 'Snapshots stockage',
                'ordering': ['-date'],
            },
        ),
    ]
