# Generated by Django 6.0.7 on 2026-07-30 14:35

from django.db import migrations, models


def update_log_actions(apps, schema_editor):
    LogAction = apps.get_model('documents', 'LogAction')
    LogAction.objects.filter(type_action='suppression').update(type_action='archivage')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_storagesnapshot'),
    ]

    operations = [
        migrations.RunPython(update_log_actions),
        migrations.AlterField(
            model_name='logaction',
            name='type_action',
            field=models.CharField(choices=[('archivage', 'Archivage'), ('rejet', 'Rejet ETL'), ('validation', 'Validation ETL'), ('modification', 'Modification')], max_length=20),
        ),
    ]
