# Generated by Django 6.0.7 on 2026-08-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_logaction_type_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='est_archive',
            field=models.BooleanField(default=False, help_text='Indique si le document a été archivé par un administrateur.'),
        ),
    ]
