# Generated by Django 6.0.7 on 2026-08-11 10:34

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_cause_rejet_en_logaction_cause_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, help_text='Empreinte du contenu : même contenu = 1 seul fichier dans MinIO', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(upload_to=apps.documents.models.document_upload_to),
        ),
    ]
