# Generated by Django 6.0.7 on 2026-08-18 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_sha256_alter_document_fichier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='est_epingle',
        ),
        migrations.AddField(
            model_name='document',
            name='epingle_par',
            field=models.ManyToManyField(blank=True, related_name='documents_epingles', to=settings.AUTH_USER_MODEL),
        ),
    ]
