# Generated by Django 6.0.7 on 2026-08-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_document_est_epingle_document_epingle_par'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='epingle_par',
        ),
        migrations.AddField(
            model_name='document',
            name='est_epingle',
            field=models.BooleanField(default=False),
        ),
    ]
