# Generated by Django 6.0.7 on 2026-08-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_remove_document_epingle_par_document_est_epingle'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apercu_pdf',
            field=models.FileField(blank=True, help_text='Aperçu PDF généré automatiquement pour les fichiers Office (pptx, docx…)', null=True, upload_to='apercus/%Y/%m/'),
        ),
    ]
